import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useParams } from 'react-router-dom';
import { AlertTriangle, Plus, ShieldAlert } from 'lucide-react';
import { Button } from '@gantry/design-system';
import { useAdminApi } from '../../api/ApiProvider';
import { ErrorState, LoadingState } from '../../components/AsyncState';

export function PlatformPage() {
  const api = useAdminApi(); const qc = useQueryClient(); const [providerName, setProviderName] = useState(''); const [credential, setCredential] = useState(''); const [poolTier, setPoolTier] = useState<'development' | 'gvisor' | 'microvm'>('development');
  const providers = useQuery({ queryKey: ['admin-platform-providers'], queryFn: () => api.listPlatformProviders() });
  const pools = useQuery({ queryKey: ['admin-platform-pools'], queryFn: () => api.listRunnerPools() });
  const createProvider = useMutation({ mutationFn: () => api.createPlatformProvider({ name: providerName, data_classes: ['internal'], credential_reference_id: credential }), onSuccess: () => { setProviderName(''); setCredential(''); void qc.invalidateQueries({ queryKey: ['admin-platform-providers'] }); } });
  const createPool = useMutation({ mutationFn: () => api.createRunnerPool({ isolation_tier: poolTier, compatible_protocols: ['gantry.runner/v1'], capacity: { max_concurrency: 1 } }), onSuccess: () => void qc.invalidateQueries({ queryKey: ['admin-platform-pools'] }) });
  const quarantine = useMutation({ mutationFn: (id: string) => api.quarantineProvider(id), onSuccess: () => void qc.invalidateQueries({ queryKey: ['admin-platform-providers'] }) });
  const drain = useMutation({ mutationFn: (id: string) => api.drainRunnerPool(id), onSuccess: () => void qc.invalidateQueries({ queryKey: ['admin-platform-pools'] }) });
  if (providers.isLoading || pools.isLoading) return <LoadingState label="Loading platform resources" />; if (providers.error || pools.error) return <ErrorState message="Platform resources could not be loaded." />;
  return <div className="admin-page"><div className="admin-page-header"><div><h1>Platform</h1><p>Organization-level provider routing and runner pool operations.</p></div></div><section className="admin-detail-block"><h2>Model providers</h2><form className="admin-form-grid" onSubmit={(e) => { e.preventDefault(); createProvider.mutate(); }}><label className="admin-field"><span className="admin-field-label">Provider name</span><input className="ds-input" value={providerName} onChange={(e) => setProviderName(e.target.value)} required /></label><label className="admin-field"><span className="admin-field-label">Credential reference</span><input className="ds-input" value={credential} onChange={(e) => setCredential(e.target.value)} required /></label><Button type="submit" disabled={createProvider.isPending}><Plus size={15} /> Register provider</Button></form><ul className="admin-detail-list">{(providers.data?.items ?? []).map((provider) => <li key={provider.id}><div><strong>{provider.name}</strong><span>{provider.state} · {provider.credential_reference_id}</span></div><div className="admin-form-row"><Link className="admin-inline-link" to={`/platform/providers/${provider.id}`}>Routes</Link><Button size="sm" variant="quiet" disabled={provider.state === 'quarantined' || quarantine.isPending} onClick={() => quarantine.mutate(provider.id)}><ShieldAlert size={14} /> Quarantine</Button></div></li>)}</ul></section><section className="admin-detail-block"><h2>Runner pools</h2><div className="admin-form-row"><select className="ds-input" value={poolTier} onChange={(e) => setPoolTier(e.target.value as typeof poolTier)}><option value="development">Development</option><option value="gvisor">gVisor</option><option value="microvm">microVM</option></select><Button size="sm" variant="secondary" onClick={() => createPool.mutate()} disabled={createPool.isPending}><Plus size={14} /> Create pool</Button></div><ul className="admin-detail-list">{(pools.data?.items ?? []).map((pool) => <li key={pool.id}><div><strong>{pool.id}</strong><span>{pool.isolation_tier} · {pool.state}</span></div><Button size="sm" variant="quiet" disabled={pool.state !== 'active' || drain.isPending} onClick={() => drain.mutate(pool.id)}><AlertTriangle size={14} /> Drain</Button></li>)}</ul></section></div>;
}

export function ProviderRoutesPage() {
  const api = useAdminApi(); const { providerId = '' } = useParams(); const routes = useQuery({ queryKey: ['admin-provider-routes', providerId], queryFn: () => api.listProviderRoutes(providerId), enabled: Boolean(providerId) });
  if (routes.isLoading) return <LoadingState label="Loading provider routes" />; if (routes.error) return <ErrorState message="Provider routes could not be loaded." />;
  return <div className="admin-page"><Link className="admin-inline-link" to="/platform">Platform</Link><div className="admin-page-header"><div><h1>Provider routes</h1><p>Allowed model metadata and route state for this provider.</p></div></div>{routes.data?.items.length ? <table className="admin-table"><thead><tr><th>Route</th><th>Models</th><th>State</th><th>ETag</th></tr></thead><tbody>{routes.data.items.map((route) => <tr key={route.id}><td>{route.id}</td><td>{route.allowed_models.join(', ')}</td><td>{route.state}</td><td>{route.etag}</td></tr>)}</tbody></table> : <p className="admin-muted">No provider routes have been registered.</p>}</div>;
}
