$schema: 'https://moonrepo.dev/schemas/project.json'

layer: 'application'
language: 'other'
tags: ['infrastructure']

tasks:
  runner-smoke:
    command: 'bash runner-smoke.sh'
    type: 'run'
    options:
      runInCI: false
