$schema: 'https://moonrepo.dev/schemas/project.json'

layer: 'application'
language: 'other'
tags: ['infrastructure']

tasks:
  up:
    command: 'docker compose -f docker-compose.yml up --build --detach'
    type: 'run'
    options:
      runInCI: false
  down:
    command: 'docker compose -f docker-compose.yml down'
    type: 'run'
    options:
      runInCI: false
  logs:
    command: 'docker compose -f docker-compose.yml logs --follow'
    type: 'run'
    options:
      runInCI: false
  smoke:
    command: 'bash smoke.sh'
    type: 'run'
    options:
      runInCI: false
  copilot-smoke:
    command: 'bash copilot-smoke.sh'
    type: 'run'
    options:
      runInCI: false
