$schema: 'https://moonrepo.dev/schemas/project.json'

type: 'application'
language: 'other'
tags: ['infrastructure']

tasks:
  up:
    command: 'docker compose -f docker-compose.yml up --build --detach'
    type: 'run'
    local: true
  down:
    command: 'docker compose -f docker-compose.yml down'
    type: 'run'
    local: true
  logs:
    command: 'docker compose -f docker-compose.yml logs --follow'
    type: 'run'
    local: true
  smoke:
    command: 'bash smoke.sh'
    type: 'test'
    local: true
  copilot-smoke:
    command: 'bash copilot-smoke.sh'
    type: 'test'
    local: true
