$schema: "https://moonrepo.dev/schemas/workspace.json"

versionConstraint: ">=2.4.6, <3.0.0"

projects:
  - "apps/*"
  - "packages/*"
  - "control-plane"
  - "runner"
  - "proto"
  - "deploy/compose"
  - "deploy/local"
  - "sidecars/*"

pipeline:
  syncProjects: false
  syncWorkspace: false

vcs:
  client: "git"
  defaultBranch: "main"
