$schema: "https://moonrepo.dev/schemas/tasks.json"

inheritedBy:
  languages: ["typescript"]

tasks:
  install:
    command: "pnpm install --frozen-lockfile"
    type: "run"
  lint:
    command: "pnpm lint"
    type: "run"
  test:
    command: "pnpm --if-present test"
    type: "test"
